defmodule Qlock.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :weekly_hours_goal, :float
    end
  end

  def down do
    alter table(:users) do
      remove :weekly_hours_goal
    end
  end
end