defmodule Qlock.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:time_entries, primary_key: false) do
      add :category_id,
          references(:categories, column: :id, name: "time_entries_category_id_fkey", type: :uuid)

      add :project_id,
          references(:projects, column: :id, name: "time_entries_project_id_fkey", type: :uuid)

      add :user_id,
          references(:users, column: :id, name: "time_entries_user_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :overtime, :boolean
      add :date, :date, null: false
      add :duration_minutes, :bigint, null: false
      add :task_name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `time_entries` table without the `time_entries_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `time_entries` table without the `time_entries_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `time_entries` table without the `time_entries_category_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:time_entries)
  end
end