defmodule Qlock.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :description, :text
    end

    alter table(:categories) do
      add :description, :text
    end
  end

  def down do
    alter table(:categories) do
      remove :description
    end

    alter table(:projects) do
      remove :description
    end
  end
end