defmodule Qlock.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:time_entries), :duration_minutes, to: :duration_seconds
  end

  def down do
    rename table(:time_entries), :duration_seconds, to: :duration_minutes
  end
end